import { ApplicationItem } from '@/lib/types';

export const seedCards: ApplicationItem[] = [
  {
    id: 1,
    company: '美团',
    role: 'AI 产品经理实习生',
    deadline: '4月22日',
    daysLeft: 2,
    status: 'apply',
    materialsDone: 2,
    materialsTotal: 4,
    stage: '待投递',
    aiTip: '优先补齐作品集后提交，截止时间紧急。',
    tag: '高优先级',
    interviewStage: '未开始',
  },
  {
    id: 2,
    company: '腾讯',
    role: '产品策划实习生',
    deadline: '4月24日',
    daysLeft: 4,
    status: 'prepare',
    materialsDone: 1,
    materialsTotal: 4,
    stage: '待准备',
    aiTip: 'JD 强调策略思考，建议先补一页项目总结。',
    tag: '目标岗位',
    interviewStage: '未开始',
  },
  {
    id: 3,
    company: '字节跳动',
    role: '增长产品实习生',
    deadline: '4月20日',
    daysLeft: 0,
    status: 'submitted',
    materialsDone: 4,
    materialsTotal: 4,
    stage: '已投递',
    aiTip: '建议准备增长实验与指标拆解类问题。',
    tag: '已完成材料',
    interviewStage: '待反馈',
  },
  {
    id: 4,
    company: '小红书',
    role: '商业化产品实习生',
    deadline: '4月26日',
    daysLeft: 6,
    status: 'assessment',
    materialsDone: 3,
    materialsTotal: 4,
    stage: '测评中',
    aiTip: '测评链接今晚到期，建议睡前完成。',
    tag: '待处理',
    interviewStage: '笔试中',
  },
  {
    id: 5,
    company: '阿里巴巴',
    role: '用户增长产品经理',
    deadline: '4月28日',
    daysLeft: 8,
    status: 'interview',
    materialsDone: 4,
    materialsTotal: 4,
    stage: '一面结束',
    aiTip: '建议今天完成面试复盘，并准备二面案例题。',
    tag: '进行中',
    interviewStage: '一面结束',
  },
  {
    id: 6,
    company: '携程',
    role: 'AI 运营产品实习生',
    deadline: '4月18日',
    daysLeft: -1,
    status: 'done',
    materialsDone: 4,
    materialsTotal: 4,
    stage: '已结束',
    aiTip: '该岗位已归档，可复用面试问题到其他岗位。',
    tag: '已归档',
    interviewStage: '已结束',
  },
];